
spring:
  application:
     name: Config-Prod
  
eureka:
  instance:
    prefer-ip-address :192.168.1.100
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
